name: GitHub Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: +test +test-fail
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        go_version: [
            1.16,
            1.15,
            1.14,
            1.13,
            1.12,
            ]
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: test zerolog with go ${{ matrix.go_version }}
        run: earthly --build-arg GO_VERSION=${{ matrix.go_version }} --ci +test
